apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-06-06T17:15:52Z"
  generation: 1
  labels:
    app: k8-scheduler
  name: k8-scheduler
  namespace: default
  resourceVersion: "42056"
  uid: babb7626-1dad-49f6-8c72-a3be94945af3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8-scheduler
    spec:
      containers:
      - image: sathishkanda83/k8s-scheduler:v1
        imagePullPolicy: IfNotPresent
        name: k8s-scheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-06T17:16:56Z"
  labels:
    app: k8-scheduler
  name: k8-scheduler
  namespace: default
  resourceVersion: "42115"
  uid: 6da31d04-da98-41c8-9ebf-93106668562d
spec:
  clusterIP: 10.102.218.222
  clusterIPs:
  - 10.102.218.222
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8-scheduler
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
