apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node
  namespace: default
    labels:
      app: k8s-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-node
  template:
    metadata:
      labels:
        app: k8s-node
    spec:
      containers:
        - name: k8s-hello-node
          image: 'k8s.gcr.io/echoserver:1.4'
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m